development:
  password: shptka_347e2a1a668ba1888e21c24cdf4d2733
  theme_id: "181742993724"
  store: jessie-demo.myshopify.com
  ignore_files:
    # 避免覆盖生产环境中的配置
    # - config/settings_data.json
    # - sections/*.json
    # 避免覆盖生产环境中的配置
    # - templates/*.json
    # 避免覆盖生产环境中的多语言文案
    # - locales/*.json
    # 生产环境不需要sourcemap文件，可注释用于本地开发或者联调解决问题
    # - assets/*.map
    # - layout